# Generated by Django 4.0.6 on 2022-07-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='veg',
        ),
        migrations.AddField(
            model_name='veg',
            name='inputs',
            field=models.ManyToManyField(to='main_app.input'),
        ),
    ]
