# Generated by Django 4.0.6 on 2022-07-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_input_cost_alter_veg_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veg',
            name='stage',
            field=models.CharField(choices=[('S', 'Seeded'), ('G', 'Growth'), ('H', 'Harvest-Ready')], default='S', max_length=1),
        ),
    ]
