# Generated by Django 4.0.6 on 2022-07-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='category',
            field=models.CharField(choices=[('Fertilizers', 'Fertilizers'), ('Pesticides', 'Pesticides'), ('Tools', 'Tools'), ('Seeds', 'Seeds')], default='Fertilizers', max_length=11),
        ),
    ]
