# Generated by Django 4.0.6 on 2022-07-27 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_merge_0008_alter_input_category_0010_profile_name'),
        ('main_app', '0015_remove_input_user_alter_veg_user'),
    ]

    operations = [
    ]
