# Generated by Django 4.0.6 on 2022-07-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=250)),
                ('cost', models.FloatField(default=0.0)),
                ('seeded', models.IntegerField(default=0)),
                ('stage', models.CharField(max_length=50)),
            ],
        ),
    ]
