# Generated by Django 4.0.6 on 2022-07-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=250)),
                ('cost', models.FloatField(default=0.0)),
                ('veg', models.ManyToManyField(to='main_app.veg')),
            ],
        ),
    ]
