# Generated by Django 4.0.6 on 2022-07-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_input_user_veg_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veg',
            name='inputs',
            field=models.ManyToManyField(blank=True, to='main_app.input'),
        ),
    ]
