# Generated by Django 4.0.6 on 2022-07-26 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_seeded_veg_planted_veg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='cost',
            field=models.FloatField(default=0.0, verbose_name='Cost ($/use)'),
        ),
        migrations.AlterField(
            model_name='veg',
            name='cost',
            field=models.FloatField(default=0.0, verbose_name='Cost ($/plant)'),
        ),
    ]
