# Generated by Django 4.0.6 on 2022-07-26 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0008_alter_veg_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='category',
            field=models.CharField(choices=[('Fertilizers', 'Fertilizers'), ('Pesticide', 'Pesticide'), ('Tools', 'Tools'), ('Seeds', 'Seeds')], default='Fertilizers', max_length=11),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenses', models.FloatField(default=0.0, verbose_name='Amount Spent ($)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
