# Generated by Django 4.0.6 on 2022-07-26 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_input_category'),
        ('main_app', '0010_profile_name'),
    ]

    operations = [
    ]
