# Generated by Django 4.0.6 on 2022-07-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_input_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veg',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='inputs',
            field=models.ManyToManyField(blank=True, to='main_app.input'),
        ),
    ]
