# Generated by Django 4.0.6 on 2022-07-27 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_input_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='user',
        ),
        migrations.AlterField(
            model_name='veg',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.profile'),
        ),
    ]
